### ISSUE TITLE
SKELETON CODE CRUD TEST TABLE 정의

### ISSUE THREAD

**Issue by jindex2411** [linewalks/Flask-Skeleton#19]
- SKELETON CODE CRUD TEST를 위한 테이블을 설계 하고 정의 합니다.
- migration 파일을 생성

**Comment by jindex2411** [comment]
### ERD 다이어그램
![ERD](https://user-images.githubusercontent.com/80883063/145939343-8256b629-af16-4524-b0fe-8f8403ebd8b6.PNG)



### SCENARIO

#### board
- 게시판 생성, 수정, 삭제 기능

#### reply
- 댓글 생성, 수정, 삭제 기능
- 게시글 삭제시 종속된 댓글들 모두 삭제

**Comment by liza0525** [comment]
기존 로그인 프로젝트랑 비슷하군요!
1. 'token_list' 테이블 명을 'token'으로 이름을 짓는 건 어떨지 싶습니다!
2. 'test_board' 테이블 명을 'board'로 짓는 건 어떤가요?

**Comment by liza0525** [comment]
클래스 reply는 의미에 있어서 '답글'의 느낌이라
댓글이라면 `comment`라고 하는 것이 알맞다고 생각합니다.
그리고 board의 content, reply의 comment들은 text, context 등이 알맞는 것 같습니다
한 번 재고해주시면 좋겠습니다!
